#!/usr/bin/env bash

declare -A DICT=( ["A"]="alpha" ["B"]="bravo" ["C"]="charlie" \
        ["D"]="delta" ["E"]="echo" ["F"]="foxtrot" ["G"]="golf" ["H"]="hotel" \
        ["I"]="india" ["J"]="juliet" ["K"]="kilo" ["L"]="lima" ["M"]="mike" \
        ["N"]="november" ["O"]="oscar" ["P"]="papa" ["Q"]="quebec" ["R"]="romeo" \
        ["S"]="sierra" ["T"]="tango" ["U"]="uniform" ["V"]="victor" ["W"]="whiskey" \
        ["X"]="x-ray" ["Y"]="yankee" ["Z"]="zulu" )

for word in $(printf '%s\n' ${DICT[@]}|tac); do
        score=${score:=0}; letter=$(head -c1 <<< ${word^^})
        clear; read -p "$letter: " nato
        [[ "${DICT[$letter],,}" == "${nato,,}" ]] && { let score++; }
        [[ $letter == "Z" ]] && { clear; echo "SCORE: ${score}/${#DICT[@]}"; }
done
