#!/usr/bin/env bash

declare -a DICT=( "alpha" "bravo" "charlie" "delta" "echo" "foxtrot" "golf" \
        "hotel" "india" "juliet" "kilo" "lima" "mike" "november" "oscar" \
        "papa" "quebec" "romeo" "sierra" "tango" "uniform" "victor" "whiskey" \
        "x-ray" "yankee" "zulu" )

for word in ${DICT[@]}; do
        score=${score:=0}
        read -p "$(head -c1 <<< ${word^^}): " answer
        [[ $word == "${answer,,}" ]] && let score++
done
echo "SCORE: ${score}/${#DICT[@]}"
